# Generated by Django 5.0.6 on 2024-07-10 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_habit_dailyhabit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='is_gym_done',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='is_read_done',
        ),
    ]
