# Generated by Django 5.0.6 on 2024-07-11 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_journal_is_gym_done_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='weight',
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measures', to=settings.AUTH_USER_MODEL)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measures', to='api.month')),
            ],
        ),
        migrations.CreateModel(
            name='DailyMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.FloatField(default=None)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_measure', to='api.journal')),
                ('measure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_measure', to='api.measure')),
            ],
        ),
    ]
