# Generated by Django 5.0.6 on 2024-07-11 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_journal_weight_measure_dailymeasure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymeasure',
            name='metric',
            field=models.FloatField(default=0.0),
        ),
    ]
